version: "3.8"
services:
  mysql:
    image: mysql:8
    container_name: mysql-obligatorio
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: obligatorio
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno123
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql               
      - ./scripts:/docker-entrypoint-initdb.d  
